# Options used by GitHub
highlighter: rouge
markdown: kramdown

# Exclude project-specific and source files when generating the site.
# TODO: Ignore .less files
exclude: [docs/, lib/, scripts/]


################################################################################
# Global variables used site-wide
################################################################################

project:
  name: Dependencies
  description: a modern Dependency Walker
  download: https://github.com/lucasg/Dependencies/releases/download/v1.8/Dependencies_x64_Release.zip
  fork: https://github.com/lucasg/Dependencies

author:
  name: lucasg
  site: https://lucasg.github.io
  email: lucasg@github
  github: lucasg

# image: assets/img/whispernote-github-banner.jpg
navbar: false

gems: [jekyll-paginate]
